---
# This playbook contains common plays that will be run on all nodes.

- name: apt install pip
  apt: name=python-pip

- name: apt install python-dev
  apt: name=python-dev

- name: pip install pip
  pip: name=pil

# for web dev
- name: pip install web.py
  pip: name=web.py

- name: pip install jinja2
  pip: name=jinja2
