---
# This playbook contains common plays that will be run on all nodes.


- name: update sources
  template: src=sources.list dest=/etc/apt/sources.list

- name: apt get update
  apt:
    update_cache: yes
    autoremove: yes

- name: apt install curl
  apt: name={{item}}
  with_items:
    - curl
    - wget

- name: apt install git
  apt: name=git

- name: apt install python-dev
  apt: name={{item}}
  with_items:
    - python-dev
    - python-pip

- name: apt install devel package
  apt: name={{item}}
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - llvm

- name: install libfreetype6-dev, libjpeg8-dev, zlib1g-dev
  apt: name={{item}}
  with_items:
    - libfreetype6-dev
    - libjpeg8-dev
    - zlib1g-dev

- name: install libxslt-dev, libxml2, libxml2-dev
  apt: name={{item}}
  with_items:
    - libxslt-dev
    - libxml2
    - libxml2-dev
