---
# This playbook contains common plays that will be run on all nodes.


- name: update to 163 sources
  template: src=sources.list dest=/etc/apt/sources.list

- name: apt get update
  shell: apt-get update

- name: apt install virtualenv
  apt: name=python-virtualenv

- name: apt install make
  apt: name=make

- name: apt install curl
  apt: name=curl

- name: apt install git
  apt: name=git

- name: install pil package
  apt: name={{item}}
  with_items:
  - libfreetype6-dev
  - libjpeg8-dev
  - zlib1g-dev

- name: install libxslt-dev, libxml2, libxml2-dev
  apt: name={{item}}
  with_items:
  - libxslt-dev
  - libxml2
  - libxml2-dev
