---
# This playbook deploys the whole application stack in this site.  
- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - python_package

- hosts: all
  sudo: yes
  tasks:
    - name: install mysql client
      apt: name=mysql-client-core-5.5
    - name: install mongo client
      apt: name=mongodb-clients
    - name: install ipython
      apt: name=ipython
    - name: install Supervisor
      pip: name=Supervisor
    - name: virtualenvwrapper
      pip: name=virtualenvwrapper
    - name: source it
      shell: source /usr/local/bin/virtualenvwrapper.sh executable=/bin/bash
    - name: load redis
      shell: docker load < /vagrant/docker_files/redis.tar.gz
    - name: load mysql
      shell: docker load < /vagrant/docker_files/mysql.tar.gz
    - name: load mongo
      shell: docker load < /vagrant/docker_files/mongo.tar.gz
