---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common
    - python_package
    - docker_pkg
    # - db
    # - django_package
    # - webpy_package