---
# This playbook deploys the whole application stack in this site.  
- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
    - python_package

- hosts: all
  sudo: yes
  tasks:
    - name: load redis
      shell: docker load < /vagrant/docker_files/redis.tar.gz
    - name: load mysql
      shell: docker load < /vagrant/docker_files/mysql.tar.gz
    - name: load mongo
      shell: docker load < /vagrant/docker_files/mysql.tar.gz
